export const enum RADIUS {
  TANK = 10,

  //i mean map block(landscape)
  BLOCK = 10,
  MISSILES = 3,
  MISSILES_BLOCK = RADIUS.BLOCK + RADIUS.MISSILES,
  MISSILES_TANK = RADIUS.TANK + RADIUS.MISSILES,
  LANDSCAPE_TANK = RADIUS.TANK + RADIUS.BLOCK,
}
