export const enum REDIS_ACTION {
  PROPAGATE_GAME = 'PROPAGATE_GAME',
  PROPAGATE_SERVER = 'PROPAGATE_SERVER',
  PROPAGATE_CLIENT = 'PROPAGATE_CLIENT',
}
export const enum REDIS_NAMESPACE {
  SUBSCRIBE = 'SUBSCRIBE',
  PUBLISH = 'PUBLISH',
}
